### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by eteohx** [modelblocks/modelblocks-release#3]
Hi. I am a student looking at trying out this toolbox.. I typically run Windows 10 on my machine so I installed a Ubuntu terminal to use this toolbox. I followed the instructions in the Quickstart file ('make') and get a string of 'ATTENTION!' messages (e.g. 'ATTENTION! I had to create config file:
 /home/eteoh/Downloads/modelblocks-release-master/config/user-numthreads.txt
which may contain an incorrect default value.
Targets with dependencies to this file may fail until it is fixed.
------------------------------------------------------------------
make: *** No rule to make target ')', needed by '/home/eteoh/Downloads/modelblocks-release-master/resource-incrsem/src/ccmodel2fjabpcptmodel.cpp'.  Stop.
make: *** No rule to make target ')', needed by '/home/eteoh/Downloads/modelblocks-release-master/resource-incrsem/src/ccmodel2fjabpcptmodel.cpp'.  Stop.
make: *** No rule to make target ')', needed by '/home/eteoh/Downloads/modelblocks-release-master/resource-incrsem/src/ccmodel2fjabpcptmodel.cpp'.  Stop.
make: *** No rule to make target ')', needed by '/home/eteoh/Downloads/modelblocks-release-master/resource-incrsem/src/ccmodel2fjabpcptmodel.d'.  Stop.
cat: /home/eteoh/Downloads/modelblocks-release-master/config/user-numthreads.txt: No such file or directory
Building source code dependencies using recursive sub-make to /home/eteoh/Downloads/modelblocks-release-master/resource-gcg/Makefile...
make: *** No rule to make target ')', needed by '/home/eteoh/Downloads/modelblocks-release-master/resource-incrsem/src/ccmodel2fjabpcptmodel.cpp'.  Stop.
Source code dependencies built and loaded.
------------------------------------------------------------------ ') in the terminal but no user-*.txt files are actually getting created in my config folder. I was wonder if you have any suggestions why this might be?

**Comment by coryshain** [comment]
Glad you're trying out ModelBlocks, eteohx, and I'll see what I can do to help. I've tried unsuccessfully to reproduce your error using a clean clone of the repository on the Windows Subsystem for Linux (WSL), so I'll need a bit more information.

1. What command did you invoke that produced this error, and from what directory? Were you just running `make` from the repository root, or had you already done that and then experienced the error trying to make the target mentioned in the Quickstart (`genmodel/wsj23.wsj02to21-nodashtags-5sm-bd-x+efabp-+c_+b5000.pcfg.tokmeasures`)?
2. How are you running Ubuntu? Are you using WSL from Windows, or do you have a dual boot setup?
3. What version of make are you using?

**Comment by eteohx** [comment]
Hi Cory, Thanks for your quick reply! Yes I believe I am using WSL (I run Windows 10 and downloaded and installed Ubuntu from the Windows Store). 
All I've done is run make from the workspace:
![image](https://user-images.githubusercontent.com/42155137/43751635-c36ff938-99cb-11e8-8321-d8625cfbf629.png)
I'm using Make 4.1.. I also tried making the target mentioned in the Quickstart and the same thing happens. I get the warnings but no text files are actually created in my config folder. 
![image](https://user-images.githubusercontent.com/42155137/43751681-ea9953a6-99cb-11e8-8676-8ec2194031f3.png)
I'm new to using Linux so perhaps I'm doing something obviously wrong! :)

**Comment by coryshain** [comment]
Ok, thanks! Your environment is very similar to the one in which I'm trying to repro the error. It looks like your target is choking when trying to process C++ dependencies. Does the following file exist on your machine:

`~/Downloads/modelblocks-release-master/resource-incrsem/src/ccmodel2fjabpcptmodel.d`

?

If so, would you mind posting its contents?

**Comment by eteohx** [comment]
It does exist. How do I see its contents? If i open it as a text file, this is what I get... 
![image](https://user-images.githubusercontent.com/42155137/43753005-9d33c14a-99d1-11e8-9797-3b441ea0965f.png)

**Comment by coryshain** [comment]
That's very helpful. As I suspected, it's not correctly inferring the C++ dependencies. Do you have g++ installed in WSL? If so, what version are you running?

**Comment by eteohx** [comment]
Well I hadn't before! But I've just installed this version:
![image](https://user-images.githubusercontent.com/42155137/43753923-1cb936e4-99d6-11e8-8c95-0fbc9c62b642.png)
I ran make from the workspace directory again but the outcome remains the same..

**Comment by coryshain** [comment]
That could be because your previous calls to make already generated mangled *.d files due to the lack of g++. Try running `git clean -xfd` from the repository root and then retrying (you'll have to remake the workspace, too).

**Comment by eteohx** [comment]
That's solved the text files problem, many thanks! The error report when i run make from the workspace informs me where to get dowload the penn-tokenizer. I have done that and have also changed the directory in the user-tokenizer-directory file. 
The resultant error report that shows up when I subsequently try to make the target (genmodel/wsj23... ) does not tell me where to download the berkeley parser though.. 
![image](https://user-images.githubusercontent.com/42155137/43754753-5bca3d98-99da-11e8-9b81-e292f042b267.png)

**Comment by coryshain** [comment]
Good, I'm glad we got that sorted! The rest should just be a matter of lining up the relevant external dependencies. Last I checked, you could get the Berkeley parser here: http://nlp.cs.berkeley.edu/software.shtml. If you want to run the target in the Quickstart, you'll also need a copy of Penn Treebank. If your department can't offer access, you'd need to buy it through the Linguistic Data Consortium, which I imagine isn't worth it just to demo Modelblocks! In that case, it might be more fruitful to have a conversation offline about your goals in using our toolbox. Feel free to email me!

**Comment by coryshain** [comment]
Ah, for what it's worth, I also just realized there are some outdated elements in the Quickstart example target that prevented the usual dependency error reporting from working for the Berkeley parser. I've fixed them in the current version of the Quickstart doc. My apologies for the confusion!

**Comment by eteohx** [comment]
Ah, great, thanks! I'll check if I can get access to Penn Treebank. Basically I found this toolbox referenced in a paper I stumbled upon and am interested in exploring the measure of embedding depth.. I'll play around with the toolbox and email you if I have any questions!
